In [72]:
import matplotlib as mpl
import matplotlib.pyplot as plt

import numpy as np
import pandas as pd
import sklearn

import os
import sys
import time

import tensorflow as tf

from tensorflow import keras


In [73]:
# 数字类型

In [74]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])

print(t)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [75]:
# 切片
print(t[:, 1:])

tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)


In [76]:
# 索引
print(t[..., 0])

tf.Tensor([1. 4.], shape=(2,), dtype=float32)


In [77]:
print(t[0, ...])

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [78]:
# 运算和普通操作
# 与整数相加
print(t + 66)

tf.Tensor(
[[67. 68. 69.]
 [70. 71. 72.]], shape=(2, 3), dtype=float32)


In [79]:
# 平方
print(tf.square(t))

tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)


In [80]:
# 乘以原矩阵的转置矩阵
print(t @ tf.transpose(t))

tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)


In [81]:
# 转换为numpy中的数组
print(t.numpy())

[[1. 2. 3.]
 [4. 5. 6.]]


In [82]:
print(type(t.numpy()))

<class 'numpy.ndarray'>


In [83]:
type(t)

tensorflow.python.framework.ops.EagerTensor

In [84]:
type(t.numpy())

numpy.ndarray

In [85]:
# 使用ndarry中的方法，平方
print(np.square(t))

[[ 1.  4.  9.]
 [16. 25. 36.]]


In [86]:
np_t = t.numpy()

In [87]:
np_t

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [88]:
print(np_t)

[[1. 2. 3.]
 [4. 5. 6.]]


In [89]:
print(type(np_t))

<class 'numpy.ndarray'>


In [90]:
# 将numpy中的数组转换为tensor
tf_t = tf.constant(np_t)
print(tf_t)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [91]:
# 标准化
a = tf.constant(2.666)

print(a.numpy())
print(a.shape)

2.666
()


In [92]:
# 字符串类型
b = tf.constant('莫')
print(b)
print(tf.strings.length(b))  # 输出字符串长度
print(tf.strings.length(b, unit='UTF8_CHAR'))  # 指定计算字符长度时，字符的编码格式
print(tf.strings.unicode_decode(b, 'UTF8'))  # 指定字符串编解码格式
print(tf.strings.unicode_decode(b, 'ascii'))

tf.Tensor(b'\xe8\x8e\xab', shape=(), dtype=string)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([33707], shape=(1,), dtype=int32)
tf.Tensor([65533 65533 65533], shape=(3,), dtype=int32)


In [93]:
# 字符串数组
t = tf.constant(['mok', 'cheung', '你好'])

# 求出数组中每一个字符串的长度
t2 = tf.strings.length(t, unit='UTF8_CHAR')
print(t2)

t3 = tf.strings.unicode_decode(t, 'UTF8')
print(t3)

tf.Tensor([3 6 2], shape=(3,), dtype=int32)
<tf.RaggedTensor [[109, 111, 107], [99, 104, 101, 117, 110, 103], [20320, 22909]]>


In [94]:
# ragged tensor 形状分布不固定的Tensor
r = tf.ragged.constant([[11, 22], [33, 44, 55], [], [666]])
print(r)
print(type(r))
print(r[:4])

<tf.RaggedTensor [[11, 22], [33, 44, 55], [], [666]]>
<class 'tensorflow.python.ops.ragged.ragged_tensor.RaggedTensor'>
<tf.RaggedTensor [[11, 22], [33, 44, 55], [], [666]]>


In [101]:
# ragged tensor 的运算和操作
r2 = tf.ragged.constant([[888, 999], [], [1024], []])
print(r2)

<tf.RaggedTensor [[888, 999], [], [1024], []]>


In [105]:
# 拼接ragged tensor
r3 = tf.concat([r, r2], axis=0)  # 沿0轴方向拼接
print(r3)
print(r3.shape)

r4 = tf.concat([r, r2], axis=1)  # 沿1轴方向拼接
print(r4)
print(r4.shape)

<tf.RaggedTensor [[11, 22], [33, 44, 55], [], [666], [888, 999], [], [1024], []]>
(8, None)
<tf.RaggedTensor [[11, 22, 888, 999], [33, 44, 55], [1024], [666]]>
(4, None)


In [109]:
# 将不规则tensor转换为规则tensor
print(r)
print(type(r))
r_2_t = r.to_tensor()  # 空白处补0，数值优先对齐，0补在后面
print(r_2_t)
print(type(r_2_t))

<tf.RaggedTensor [[11, 22], [33, 44, 55], [], [666]]>
<class 'tensorflow.python.ops.ragged.ragged_tensor.RaggedTensor'>
tf.Tensor(
[[ 11  22   0]
 [ 33  44  55]
 [  0   0   0]
 [666   0   0]], shape=(4, 3), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [115]:
# sparse tensor 稀疏分布的tensor，可以自定义数值的位置和填补位置
s = tf.SparseTensor(indices=[[0, 1], [1, 0], [2, 2]],
                   values=[666., 888., 999.],
                   dense_shape=[4, 4])

print(type(s))
print(s)  # 返回的sparsetensor对象是将每个数值的位置记录下来，并不会主动去填补0
s_2_t = tf.sparse.to_dense(s)  # 将sparsetensor转换为tensor，自动添加零
print(s_2_t)
print(type(s_2_t))

<class 'tensorflow.python.framework.sparse_tensor.SparseTensor'>
SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 2]], shape=(3, 2), dtype=int64), values=tf.Tensor([666. 888. 999.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))
tf.Tensor(
[[  0. 666.   0.   0.]
 [888.   0.   0.   0.]
 [  0.   0. 999.   0.]
 [  0.   0.   0.   0.]], shape=(4, 4), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [124]:
# 稀疏tensor上的运算和基本操作
# 与数值相乘
s2 = s * 2.0
print(s2)
s2_2_t = tf.sparse.to_dense(s2)
print(s2_2_t)

# unsupported operand type(s) 
# for +: 'SparseTensor' and 'int'
# 不支持加法运算
try:
    s3 = s2 + 666
except TypeError as te:
    print(te)

s4 = tf.constant([[10., 20.],
                  [30., 40.],
                  [50., 60.],
                  [70., 80.]])

# 稀疏tensor与密集tensor相乘
print(tf.sparse.sparse_dense_matmul(s, s4))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 2]], shape=(3, 2), dtype=int64), values=tf.Tensor([1332. 1776. 1998.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))
tf.Tensor(
[[   0. 1332.    0.    0.]
 [1776.    0.    0.    0.]
 [   0.    0. 1998.    0.]
 [   0.    0.    0.    0.]], shape=(4, 4), dtype=float32)
unsupported operand type(s) for +: 'SparseTensor' and 'int'
tf.Tensor(
[[19980. 26640.]
 [ 8880. 17760.]
 [49950. 59940.]
 [    0.     0.]], shape=(4, 2), dtype=float32)


In [135]:
s5 = tf.SparseTensor(indices=[[0, 1], [2, 3], [2, 1]],
                    values=[1., 2.6, 3.5],
                    dense_shape=[3, 4])
print(s5)

# 直接将s5转换会因为下标排序问题而报错，因此需要重新对下标进行排序再转换
# print(tf.sparse.to_dense(s5))

# 排序
s6 = tf.sparse.reorder(s5)
print(s6)
print(tf.sparse.to_dense(s6))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [2 3]
 [2 1]], shape=(3, 2), dtype=int64), values=tf.Tensor([1.  2.6 3.5], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
SparseTensor(indices=tf.Tensor(
[[0 1]
 [2 1]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1.  3.5 2.6], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[0.  1.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  3.5 0.  2.6]], shape=(3, 4), dtype=float32)


In [155]:
# 变量
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
print(v)
print(type(v))
print(v.value())  # 变量中的值
print(v.value()[1])  # 变量中的值，使用下标获得不同维的值，返回的类型是tensor

print(v.numpy())  # 转换为numpy的数组
print(v)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
tf.Tensor([4. 5. 6.], shape=(3,), dtype=float32)
[[1. 2. 3.]
 [4. 5. 6.]]
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>


In [160]:
# 运算与基本操作
# print(v)
v.assign(2 * v)  # 将变量与数值相乘
# print(v)
v[0, 1].assign(666)  # 改变某个位置的值
v[1].assign([888., 999., 1010])  # 修改某行数值
print(v.numpy())

[[  32.  666.   96.]
 [ 888.  999. 1010.]]


In [161]:
# 直接使用python原生列表取下标赋值的方法会报错
try:
    v[1] = [111., 222., 333.]
except TypeError as ex:
    print(ex)

'ResourceVariable' object does not support item assignment
